// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB2X27y2zqbG0A26ORZ84ptGgnWMFWfcE',
    appId: '1:132678019005:web:782e5817a86f2469d714d4',
    messagingSenderId: '132678019005',
    projectId: 'medic-484c1',
    authDomain: 'medic-484c1.firebaseapp.com',
    storageBucket: 'medic-484c1.appspot.com',
    measurementId: 'G-Z1V96SGLJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQv3fuFkGG9oNyT9Dg65BCTldrFJQjyls',
    appId: '1:132678019005:android:fbcfa1a3540b1bf3d714d4',
    messagingSenderId: '132678019005',
    projectId: 'medic-484c1',
    storageBucket: 'medic-484c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDzGs9lnoajhvT_G879Z04KXeBewxKbKU',
    appId: '1:132678019005:ios:333488ceb557219fd714d4',
    messagingSenderId: '132678019005',
    projectId: 'medic-484c1',
    storageBucket: 'medic-484c1.appspot.com',
    iosClientId: '132678019005-po4917ue21stfep3g9f59deaoc01v2sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.medic',
  );
}
